import { StyleSheet } from "react-native";
import { COLORS } from "@constants/colors";

export const translateStyles = StyleSheet.create({
  // Saved translations styles
  translationsSection: { marginBottom: 16 },
  sectionTitle: {
    color: COLORS.text,
    fontSize: 13,
    fontWeight: "600",
    marginBottom: 8,
  },
  translationsList: { maxHeight: 140, overflow: "hidden" },
  translationItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.surfaceLight,
    borderRadius: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  translationItemActive: { borderColor: COLORS.success },
  translationInfo: { flex: 1, padding: 12 },
  translationHeader: { flexDirection: "row", alignItems: "center", gap: 6 },
  translationConfig: { color: COLORS.text, fontSize: 13, fontWeight: "500" },
  translationDate: { color: COLORS.textMuted, fontSize: 11, marginTop: 2 },
  deleteBtn: { padding: 12 },

  // Config picker styles
  configPicker: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: COLORS.surfaceLight,
    borderRadius: 12,
    padding: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  configPickerLeft: { flexDirection: "row", alignItems: "center", gap: 10 },
  configPickerText: { color: COLORS.text, fontSize: 14, fontWeight: "500" },
  configDropdown: {
    backgroundColor: COLORS.surfaceLight,
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    overflow: "hidden",
  },
  configOption: {
    padding: 14,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  configOptionActive: { backgroundColor: COLORS.surfaceElevated },
  configOptionText: { color: COLORS.text, fontSize: 14 },
  configOptionTextActive: { color: COLORS.primary, fontWeight: "600" },

  // Progress styles
  progressContainer: {
    backgroundColor: COLORS.surfaceLight,
    borderRadius: 12,
    padding: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: COLORS.primary,
  },
  progressHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  progressTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
  },
  progressTitle: {
    color: COLORS.text,
    fontSize: 14,
    fontWeight: "500",
  },
  progressCount: {
    color: COLORS.primary,
    fontSize: 14,
    fontWeight: "700",
  },
  keyStatusText: {
    color: COLORS.textMuted,
    fontSize: 12,
    marginTop: 6,
    marginLeft: 30,
  },
  batchGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 12,
  },
  batchItem: {
    width: 44,
    height: 32,
    borderRadius: 8,
    backgroundColor: COLORS.surfaceElevated,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    gap: 4,
  },
  batchCompleted: { backgroundColor: COLORS.success },
  batchProcessing: { backgroundColor: COLORS.primary },
  batchError: { backgroundColor: COLORS.error },
  batchItemText: { color: COLORS.text, fontSize: 12, fontWeight: "600" },

  // Advanced options styles
  advancedToggle: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 8,
    marginBottom: 8,
  },
  advancedToggleText: {
    color: COLORS.textMuted,
    fontSize: 13,
  },
  advancedPanel: {
    backgroundColor: COLORS.surfaceLight,
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  advancedRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  advancedRowLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
  },
  advancedRowInfo: { flex: 1 },
  advancedRowTitle: {
    color: COLORS.text,
    fontSize: 13,
    fontWeight: "500",
  },
  advancedRowDesc: {
    color: COLORS.textMuted,
    fontSize: 11,
    marginTop: 2,
  },
  rangeInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
  },
  rangeInputGroup: {
    alignItems: "center",
    gap: 4,
  },
  rangeLabel: {
    color: COLORS.textMuted,
    fontSize: 11,
  },
  rangeInput: {
    backgroundColor: COLORS.surfaceElevated,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    color: COLORS.text,
    fontSize: 14,
    fontWeight: "500",
    minWidth: 80,
    textAlign: "center",
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  durationHint: {
    color: COLORS.textMuted,
    fontSize: 11,
    textAlign: "center",
    marginTop: 8,
  },

  // Warning styles
  warningContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,183,77,0.15)",
    borderRadius: 10,
    padding: 12,
    marginBottom: 12,
    gap: 10,
    borderWidth: 1,
    borderColor: COLORS.warning,
  },
  warningText: {
    color: COLORS.warning,
    fontSize: 13,
    flex: 1,
  },
});
