import { StyleSheet } from "react-native";
import { COLORS } from "@constants/colors";

export const queueStyles = StyleSheet.create({
  // Tab styles
  tabBar: {
    flexDirection: "row",
    marginHorizontal: 16,
    backgroundColor: COLORS.surface,
    borderRadius: 12,
    padding: 4,
    marginBottom: 12,
  },
  tab: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    borderRadius: 8,
    gap: 6,
  },
  tabActive: { backgroundColor: COLORS.surfaceElevated },
  tabText: { color: COLORS.textMuted, fontSize: 13, fontWeight: "500" },
  tabTextActive: { color: COLORS.text },
  badge: {
    backgroundColor: COLORS.textMuted,
    borderRadius: 10,
    paddingHorizontal: 6,
    paddingVertical: 2,
    minWidth: 20,
    alignItems: "center",
  },
  badgeActive: { backgroundColor: COLORS.primary },
  badgeProcessing: { backgroundColor: COLORS.warning },
  badgeCompleted: { backgroundColor: COLORS.success },
  badgeText: { color: COLORS.background, fontSize: 11, fontWeight: "600" },

  // Queue item styles
  queueItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.surface,
    borderRadius: 12,
    marginBottom: 10,
    overflow: "hidden",
    minHeight: 78,
  },
  thumbnail: {
    width: 120,
    height: 68,
    backgroundColor: COLORS.surfaceLight,
    flexShrink: 0,
  },
  progressOverlay: {
    position: "absolute",
    left: 0,
    top: 0,
    width: 120,
    height: 68,
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "center",
    alignItems: "center",
  },
  progressText: { color: COLORS.text, fontSize: 14, fontWeight: "700" },
  itemInfo: { flex: 1, padding: 10 },
  itemTitle: {
    color: COLORS.text,
    fontSize: 12,
    fontWeight: "500",
    lineHeight: 16,
  },
  itemMeta: { flexDirection: "row", gap: 6, marginTop: 4 },
  metaText: { color: COLORS.textMuted, fontSize: 11 },
  itemFooter: { marginTop: 4 },
  dateText: { color: COLORS.textMuted, fontSize: 11 },
  itemActions: { justifyContent: "center", paddingRight: 8, gap: 4 },
  actionBtn: { padding: 6 },
  actionBtnDisabled: { opacity: 0.5 },

  // Config picker styles
  configPicker: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: COLORS.surface,
    borderRadius: 10,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  configPickerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flex: 1,
  },
  configPickerText: {
    color: COLORS.text,
    fontSize: 13,
    fontWeight: "500",
    flex: 1,
  },
  configDropdown: {
    backgroundColor: COLORS.surface,
    borderRadius: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
    overflow: "hidden",
  },
  configOption: {
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  configOptionActive: { backgroundColor: COLORS.surfaceElevated },
  configOptionText: { color: COLORS.text, fontSize: 13 },
  configOptionTextActive: { color: COLORS.primary, fontWeight: "600" },

  // Action section styles
  actionSection: {
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  actionButtons: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  actionButtonPrimary: { flex: 1 },
  clearAllBtn: {
    width: 44,
    height: 44,
    borderRadius: 10,
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    justifyContent: "center",
    alignItems: "center",
  },
  clearAllBtnFull: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.error,
    borderRadius: 10,
    paddingVertical: 10,
    gap: 8,
  },
  clearAllText: {
    color: COLORS.error,
    fontSize: 14,
    fontWeight: "500",
  },
  warningContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,183,77,0.15)",
    borderRadius: 10,
    padding: 10,
    marginBottom: 8,
    gap: 8,
    borderWidth: 1,
    borderColor: COLORS.warning,
  },
  warningText: {
    color: COLORS.warning,
    fontSize: 12,
    flex: 1,
  },

  // Empty & pagination styles
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    gap: 12,
  },
  emptyText: { color: COLORS.textMuted, fontSize: 14 },
  pagination: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    gap: 16,
  },
  pageBtn: { padding: 8 },
  pageBtnDisabled: { opacity: 0.4 },
  pageText: { color: COLORS.text, fontSize: 14 },
});
